Metrics/LineLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/*'

Style/Documentation:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'kingsly-certbot.gemspec'

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Max: 36

Metrics/ParameterLists:
  Exclude:
    - 'lib/kingsly_certbot/kingsly_client.rb'

Style/GlobalVars:
  AllowedVariables:
    - '$logger'

Style/RedundantReturn:
  Enabled: false