Metrics/LineLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/*'

Style/Documentation:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*'

Metrics/PerceivedComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Max: 36
